### ISSUE TITLE
Dataset in CoronaWhy Dataverse 

### ISSUE THREAD

**Issue by geek80** [Covid-Nein-Team/TheSoundOfSilence#1]
Hello,Your dataset was added to CoronaWhy (https://www.coronawhy.org/) Data Lake on Dataverse  as a piece of common COVID-19 dataframe http://datasets.coronawhy.org/dataset.xhtml?persistentId=doi:10.5072/FK2/HQ7ZGI

Would you be willing to help with maintenance of your dataset in Dataverse, e.g. adding the relevant metadata and keeping the dataset up-to-date? That will help to make the dataset findable and accessible for medical science community.

**Comment by ap--** [comment]
He @geek80

all the datasets in this repository have been derived form other datasets that are available online and carry no additional scientific value. They were used for the SpaceApps COVID-19 hackathon.
I believe adding them to a larger collection of Covid related data, will just increase the noise.

Let me know what you think,
Cheers,
Andreas

**Comment by geek80** [comment]
I understand. Thank you.

**Comment by k-goncharova** [comment]
Thank you for your comment, @ap-- . We've made deaccession of your dataset from CoronaWhy Dataverse. You're right, our goal is to make a trustworthy source of information on COVID-19, not just add some noise.

**Comment by ap--** [comment]
Resolved 😃  Closing.
